parsers:
- ./parsers/s01-parse/crowdsecurity/exchange-pop-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: exchange-pop-logs.log
log_type: exchange-pop
labels: {}
ignore_parsers: false
