parsers:
- crowdsecurity/nginx-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/http-logs
scenarios:
- ./scenarios/crowdsecurity/http-xss-probing.yaml
postoverflows:
- ""
log_file: nginx-http-xss-probing.log
log_type: nginx
ignore_parsers: true
