parsers:
- crowdsecurity/nginx-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/http-backdoors-attempts
postoverflows:
- ""
log_file: nginx-http-backdoor.log
log_type: nginx
ignore_parsers: true
