parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/postfix-very-slow-bf.yaml
log_file: postfix-very-slow-bf.log
log_type: syslog
