parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/auditd-logs.yaml
scenarios:
- ./scenarios/crowdsecurity/auditd-postexploit-exec-from-net.yaml
postoverflows:
- ""
log_file: auditd-curl-exec-behavior.log
log_type: auditd
labels: {}
ignore_parsers: false
override_statics: []
