parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/Zaulao/aws-alb.yaml
- crowdsecurity/http-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: aws-alb-logs.log
log_type: aws-alb
