parsers:
- crowdsecurity/cri-logs
- parsers/s01-parse/yanis-kouidri/envoy-logs.yaml
- crowdsecurity/http-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/http-crawl-non_statics
postoverflows:
- ""
log_file: envoy-http-crawl-non_statics.log
log_type: containerd
ignore_parsers: true
labels:
    program: envoy
