parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/mwinters_stuff/mailu-admin-logs.yaml
scenarios:
- ./scenarios/mwinters_stuff/mailu-admin-bf.yaml
postoverflows:
- ""
log_file: mailu-admin-bf.log
log_type: mailu-admin
labels: {}
ignore_parsers: true
override_statics: []
