parsers:
- crowdsecurity/sshd-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/ssh-bf
postoverflows:
- ""
log_file: ssh-bf.log
log_type: syslog
ignore_parsers: false
