parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/sshd-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/ssh-ultra-slow-bf.yaml
log_file: ssh-ultra-slow-bf.log
log_type: syslog
