parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/dateparse-enrich
  - ./parsers/s01-parse/crowdsecurity/supavisor-logs.yaml
scenarios:
  - ./scenarios/crowdsecurity/supavisor-bf.yaml
postoverflows:
  - ""
log_file: supavisor-logs.log
log_type: supavisor
ignore_parsers: false
