parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/dovecot-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/dovecot-very-slow-bf.yaml
log_file: dovecot-very-slow-bf.log
log_type: syslog
