parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - ./parsers/s01-parse/LearningSpot/ispconfig-logs.yaml
scenarios:
    - ./scenarios/LearningSpot/ispconfig-bf.yaml
postoverflows:
    - ""
log_file: ispconfig-bf.log
log_type: ispconfig
ignore_parsers: true
