parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/docker-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/LePresidente/adguardhome-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: adguardhome-logs.log
log_type: adguardhome
labels: {}
ignore_parsers: false
override_statics: []
