parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/crowdsecurity/thehive-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: thehive-logs.log
log_type: thehive
labels: {}
ignore_parsers: false
override_statics: []
