bucket_input: bucket_input.yaml                
bucket_results: bucket_results.yaml             
#configuration
index: "./config/hub/.index.json"
configurations:      
  scenarios:
  - crowdsecurity/http-sqli-probing
