parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/klausagnoletti/opnsense-openvpn-logs.yaml 
scenarios:
- ""
postoverflows:
- ""
log_file: opnsense-openvpn-logs.log
log_type: opnsense-openvpn
labels: {}
ignore_parsers: false
