parsers:
    - crowdsecurity/cri-logs
    - ./parsers/s01-parse/yanis-kouidri/envoy-logs.yaml
    - crowdsecurity/http-logs
    - crowdsecurity/dateparse-enrich
scenarios:
    - ""
postoverflows:
    - ""
log_file: envoy.log
log_type: containerd
labels: 
    program: envoy
