parsers:
  - LearningSpot/ispconfig-logs
scenarios:
  - LearningSpot/ispconfig-bf
description: "ISPConfig parser and brute-force detection"
author: LearningSpot
tags:
  - linux
  - brute-force
  - ispconfig
