parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/nginx-logs
scenarios:
postoverflows:
- ""
log_file: pfsense-rfc5424-nginx.log
log_type: syslog
labels: {}
ignore_parsers: false

