parsers:
- ./parsers/s01-parse/crowdsecurity/exchange-smtp-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/exchange-bf.yaml
postoverflows:
- ""
log_file: exchange-smtp-bf.log
log_type: exchange-smtp
labels: {}
ignore_parsers: false
