parsers:
    - ./parsers/s01-parse/nicoh88/proxmox-backup-auth-logs.yaml
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
scenarios:
    - ""
postoverflows:
    - ""
log_file: proxmox-backup-auth-logs.log
log_type: proxmox-backup-auth
