parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/postfix-helo-very-slow.yaml
log_file: postfix-helo-very-slow.log
log_type: syslog
