parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- parsers/s01-parse/jusabatier/apereo-cas-audit-logs.yaml
scenarios:
- scenarios/jusabatier/apereo-cas-slow-bf.yaml
postoverflows:
- ""
log_file: apereo-cas-slow-bf.log
log_type: cas
ignore_parsers: false
