parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/baudneo/zoneminder-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: zoneminder-web_php.log
log_type: zoneminder
labels: {}
ignore_parsers: true
