parsers:
- crowdsecurity/smb-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/smb-slow-bf.yaml
postoverflows:
- ""
log_file: smb-slow-bf.log
log_type: syslog
ignore_parsers: true

