parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - ./parsers/s01-parse/cyrille37/sympa_ww-logs.yaml
scenarios:
    #- ""
    - ./scenarios/cyrille37/sympa_ww-http-scan.yaml
postoverflows:
    - ""
log_file: sympa_ww-logs.log
log_type: syslog
ignore_parsers: false

