parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/auditd-logs.yaml
scenarios:
- ./scenarios/crowdsecurity/auditd-postexploit-rm.yaml
postoverflows:
- ""
log_file: auditd-rm-sus-behaviour.log
log_type: auditd
labels: {}
ignore_parsers: true
override_statics: []
