parsers:
- crowdsecurity/apache2-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/netgear_rce.yaml
postoverflows:
- ""
log_file: netgear_rce.log
log_type: apache2
labels: {}
ignore_parsers: true
override_statics: []
