parsers:
- ./parsers/s01-parse/crowdsecurity/endlessh-logs.yaml
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/endlessh-bf.yaml
postoverflows:
- ""
log_file: endlessh-logs.log
log_type: endlessh
ignore_parsers: false
