bucket_input: bucket_input.yaml                 #unused in our example
bucket_results: bucket_results.yaml              #unused in our example

#configuration
index: "./config/hub/.index.json"
configurations:      
  scenarios:
  - firewallservices/zimbra-bf
