parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/PintjesB/technitium-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - "./scenarios/PintjesB/technitium-bf.yaml"
postoverflows:
    - ""
log_file: technitium.log
log_type: technitium
