parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/sshd-logs.yaml
scenarios:
- ./scenarios/crowdsecurity/ssh-preauth-scan.yaml
postoverflows:
- ""
log_file: ssh-preauth-scan.log
log_type: syslog
labels: {}
ignore_parsers: true
