parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/MariuszKociubinski/bitwarden-logs.yaml
scenarios:
postoverflows:
log_file: bitwarden-logs.log
log_type: bitwarden
ignore_parsers: false
