parsers:
- ./parsers/s01-parse/crowdsecurity/traefik-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/http-logs
scenarios:
- crowdsecurity/http-generic-bf
postoverflows:
- ""
log_file: traefik_generic-bf.log
log_type: traefik
labels: {}
ignore_parsers: false
