parsers:
- crowdsecurity/vsftpd-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/vsftpd-slow-bf.yaml
postoverflows:
- ""
log_file: vsftpd-slow-bf.log
log_type: vsftpd
ignore_parsers: true

