parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - ./parsers/s01-parse/melite/postfix-submission-auth.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - ""
log_file: postfix-submission-auth.log
log_type: syslog
