parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/schiz0phr3ne/radarr-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: radarr-logs.log
log_type: syslog
labels: {}
ignore_parsers: false
override_statics: []
