parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/geoip-enrich
- ./parsers/s01-parse/crowdsecurity/vsftpd-success-logs.yaml
scenarios:
- "./scenarios/crowdsecurity/impossible-travel.yaml"
log_file: vsftpd-success-logs.log
log_type: vsftpd
ignore_parsers: true

