log_file:  mysql.log #unused for now, will need rework when acquis.yaml will part of parsers
parser_results: parser_results.json
bucket_input: bucket_input.yaml
bucket_results: bucket_result.json
postoverflow_input: postoverflow_input.yaml
postoverflow_results: postoverflow_results.json

#configuration
index: "./config/hub/.index.json"
configurations:
  parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/mysql-logs
