parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/Azlaroc/sftpgo-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios: []
postoverflows: []
log_file: sftpgo-logs.log
log_type: sftpgo
ignore_parsers: false
