parser_input: parser_input.yaml
parser_results: parser_results.yaml

marshaled_time_year: 2020

#configuration
index: "./config/hub/.index.json"
configurations:      
  parsers:
  - crowdsecurity/dateparse-enrich
