parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/Zaulao/aws-alb.yaml
- crowdsecurity/http-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/http-bad-user-agent
postoverflows:
- ""
log_file: aws-alb-http-bad-user-agent.log
log_type: aws-alb
ignore_parsers: true

