parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - ./parsers/s01-parse/LearningSpot/ispconfig-logs.yaml
scenarios:
    - ""
postoverflows:
    - ""
log_file: ispconfig-logs.log
log_type: ispconfig
