parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/sshd-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/ssh-glacial-bf.yaml
log_file: ssh-glacial-bf.log
log_type: syslog
