parsers:
- ./parsers/s01-parse/fulljackz/proxmox-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/fulljackz/proxmox-bf.yaml
postoverflows:
- ""
log_file: proxmox-bf.log
log_type: syslog
labels: {}
ignore_parsers: false
