parsers:
- fulljackz/proxmox-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- fulljackz/proxmox-bf
postoverflows:
- ""
log_file: proxmox-bf.log
log_type: syslog
labels: {}
ignore_parsers: true
