parsers:
- ./parsers/s01-parse/crowdsecurity/exchange-imap-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: exchange-imap-logs.log
log_type: exchange-imap
labels: {}
ignore_parsers: false
