parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/apache2-logs
- crowdsecurity/dateparse-enrich
scenarios:
- "./scenarios/baudneo/zoneminder_cve-2022-39290.yaml"
postoverflows:
- ""
log_file: zoneminder_cve-39290.log
log_type: apache2
labels: {}
ignore_parsers: true
override_statics: []
