parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/mwinters_stuff/mailu-admin-logs.yaml
scenarios:
 - ""
postoverflows:
- ""
log_file: mailu-admin-logs.log
log_type: mailu-admin
labels: {}
ignore_parsers: false
override_statics: []

