parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/melite/sshd-preauth-disconnect.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - ""
log_file: sshd-preauth-disconnect.log
log_type: syslog
