# ISPConfig Bruteforce
type: leaky
name: LearningSpot/ispconfig-bf
description: "Detect ISPConfig Bruteforce"
filter: evt.Meta.log_type == 'ispconfig_failed_auth'
groupby: evt.Meta.source_ip
leakspeed: 1m
capacity: 5
blackhole: 1m
labels:
  service: ispconfig
  classification:
    - attack.T1110
  behavior: "http:bruteforce"
  confidence: 3
  spoofable: 0
  label: "ISPConfig Bruteforce"
  remediation: true
---
# ISPConfig User Enumeration
type: leaky
name: LearningSpot/ispconfig_bf_user_enum
description: "Detect ISPConfig User Enumeration Bruteforce"
filter: evt.Meta.log_type == 'ispconfig_failed_auth'
distinct: evt.Meta.target_user
groupby: evt.Meta.source_ip
leakspeed: 1m
capacity: 5
blackhole: 1m
labels:
  service: ispconfig
  classification:
    - attack.T1589
    - attack.T1110
  behavior: "http:bruteforce"
  confidence: 3
  spoofable: 0
  label: "ISPConfig User Enumeration"
  remediation: true
