parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/pgsql-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/pgsql-bf
postoverflows:
- ""
log_file: pgsql-logs.log
log_type: postgres
ignore_parsers: false
