parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/exim-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: exim-logs.log
log_type: exim
labels: {}
ignore_parsers: false
override_statics: []
