parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/a1ad/meshcentral-logs.yaml
scenarios:
- ./scenarios/a1ad/meshcentral-bf.yaml
postoverflows:
- ""
log_file: meshcentral-bf.log
log_type: meshcentral
labels: {}
ignore_parsers: false
override_statics: []
