name: Delete branch from external dispatch

on:
  repository_dispatch:
    types: ['delete_branch']

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ github.event.client_payload.version }}