parsers:
- crowdsecurity/syslog-logs
- ./parsers/s01-parse/baudneo/gotify-logs.yaml
scenarios:
#- ./scenarios/baudneo/gotify-bf.yaml
- ""
postoverflows:
- ""
log_file: gotify-logs.log
log_type: gotify
labels: {}
ignore_parsers: false
